[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle internationalization redirects
[[redirects]]
  from = "/fr/*"
  to = "/fr/:splat"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/:splat"
  status = 200

# Default redirect to French
[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/fr/index.html"
  status = 200 